language: dart
sudo: false

# Run against the dev channel.
dart:
  - dev

# Run tests and formatting checks.
dart_task:
  - test: --platform vm
  - dartfmt

# Analyze code and examples.
script:
  - dartanalyzer lib test
  - for example in example/*; do (cd $example; echo [Analyzing $example]; pub get; dartanalyzer .); done
  - (cd interop; echo [Analyzing interop]; pub get; dartanalyzer .)

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/.pub-cache
