language: dart

# necessary to avoid chrome sandboxing issues
sudo: required
addons:
  chrome: stable

# The Chrome addon does not work on windows
install:
  - pub get
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install googlechrome ; fi

# Run against both the dev and stable channel.
dart:
  - stable
  - dev

# Define test tasks to run.
dart_task:
  - test: --platform vm
  - test: --platform chrome
  - dartfmt: true
  - dartanalyzer: --fatal-warnings lib

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - $HOME/.pub-cache
