language: dart
sudo: false

# Run against dev and stable channels.
dart:
  - dev
  - stable

# Define test tasks to run.
dart_task:
  - test: --platform vm

# Only run one instance of the formatter and the analyzer, rather than running
# them against each Dart version.
matrix:
  include:
  - dart: stable
    dart_task: dartfmt
  # Wish we could exclude `examples` in `analysis_options.yaml` but it seems
  # blocked by https://github.com/dart-lang/sdk/issues/26212
  - dart: dev
    dart_task: dartanalyzer lib test

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

os:
  - linux
  - osx
  
cache:
  directories:
    - $HOME/.pub-cache
