language: dart

# necessary to avoid chrome sandboxing issues
sudo: required
addons:
  chrome: stable

# The Chrome addon does not work on windows
install:
  - pub get --no-precompile
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install googlechrome ; fi

# Run against both the dev and stable channel.
dart:
  - stable
  - dev

script:
  - env
#  if [$]
#  for example in example/*; do (cd $example; echo [Analyzing $example]; pub get; dartanalyzer .); done
#  fi
  - dartfmt -n lib
  - dartanalyzer
  - pub run test --platform=vm
  - pub run test --platform=chrome


# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - $HOME/.pub-cache
