language: dart

# necessary to avoid chrome sandboxing issues
sudo: required
addons:
  chrome: stable

# The Chrome addon does not work on windows
install:
  - pub get --no-precompile
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install googlechrome ; fi

# Run against both the dev and stable channel.
dart:
  - stable
  - dev

script:

  - |
    if [$TRAVIS_DART_VERSION = stable]; then
      function format_analyze() {
        pushd $1
        pub get --no-precompile && dartfmt -n lib && dartanalyzer .
        local result=$?
        popd
        return result
      }

      format_analyze(.)
      format_analyze(interop)
      for example in example/*; do
         format_analyze($example)
      done
    fi
  - pub run test --platform=vm
  - pub run test --platform=chrome


# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - $HOME/.pub-cache
