name: grpc
description: Dart implementation of gRPC.
version: 0.0.1
#homepage: https://www.example.com

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  async:
  meta:
  http2:

dev_dependencies:
  test: ^0.12.0
