name: grpc
description: Dart implementation of gRPC, a high performance, open-source universal RPC framework.

version: 2.0.0

author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  googleapis_auth: ^0.2.5+3
  meta: ^1.0.5
  http: '>=0.11.3+17 <0.13.0'
  http2: '>=0.1.7 <2.0.0'

dev_dependencies:
  build_runner: ^1.5.2
  build_test: ^0.10.8
  build_web_compilers: ^2.1.1
  mockito: ^4.0.0
  test: ^1.6.4
