name: grpc
description: Dart implementation of gRPC, a high performance, open-source universal RPC framework.

version: 3.0.0-nullsafety.0

homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  archive: ^3.0.0-nullsafety
  async: ^2.2.0
  crypto: ^3.0.0-nullsafety
  fixnum: ^1.0.0-nullsafety
  googleapis_auth: ^1.0.0-nullsafety
  meta: ^1.1.6
  http: ^0.13.0-nullsafety
  http2: ^2.0.0-nullsafety
  protobuf: ^2.0.0-nullsafety.1

dev_dependencies:
  build_runner: ^1.11.0
  build_test: ^1.3.4
  mockito: ^5.0.0-nullsafety.5
  test: ^1.16.0-nullsafety.16
  stream_channel: ^2.0.0
  stream_transform: ^2.0.0-nullsafety

dependency_overrides:
  shelf:
    version: ^1.0.0-nullsafety
