name: grpc
description: Dart implementation of gRPC.
version: 0.6.4
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  googleapis_auth: ^0.2.3+6
  meta: ^1.0.5
  http: ^0.11.3+16
  http2: ^0.1.7

dev_dependencies:
  build_runner: ^0.10.0
  build_test: ^0.10.3
  build_web_compilers: ^0.4.3
  mockito: ^3.0.0
  test: ^1.3.0
