name: grpc
description: Dart implementation of gRPC.
version: 0.0.1
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  async: ^1.13.3
  meta: ^1.0.5
  http2: ^0.1.3

dev_dependencies:
  mockito: ^2.0.2
  test: ^0.12.0
