name: grpc
description: Dart implementation of gRPC, a high performance, open-source universal RPC framework.
version: 1.0.3
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  async: ^2.2.0
  googleapis_auth: ^0.2.7
  meta: ^1.1.7
  http: ^0.12.0
  http2: ^1.0.0

dev_dependencies:
  mockito: ^4.1.0
  test: ^1.6.4
