name: isolate_service
description: Dart gRPC sample client and server.
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  async: ^2.2.0
  grpc:
    path: ../../
  protobuf: ^1.0.1
  isolate: ^2.0.2
  logging: ^0.11.3

dev_dependencies:
  test: ^1.6.4
