name: grpc_or_grpcweb
description: sample client switching automatically between gRPC and gRPC-web
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  grpc:
    path: ../../
  protobuf: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
