name: grpc_web
description: Dart gRPC-Web sample client
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  grpc:
    path: ../../
  protobuf: ^2.0.0-nullsafety

dev_dependencies:
  build_runner: ^1.5.2
