name: route_guide
description: Dart gRPC sample client and server.
version: 0.0.1
#homepage: https://www.example.com

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  async:
  grpc:
    path: ../../
  protobuf:
  http2:

dev_dependencies:
  test: ^0.12.0
