language: dart
sudo: false

# Run against dev and stable channels.
dart:
  - dev
  - stable
# Define test tasks to run.
dart_task:
  # Run the tests -- include the default-skipped presubmit tests.
  - test: --platform vm --run-skipped
  - dartfmt
  - dartanalyzer

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
