name: googleapis
description: Dart gRPC client sample for Google APIs
version: 0.0.1
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  async: '>=1.13.3 <3.0.0'
  grpc:
    path: ../../
  protobuf: ^0.7.0

dev_dependencies:
  test: ^0.12.0
