name: interop
description: Dart gRPC interoperability test suite.
version: 0.0.1
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  args: ^0.13.0
  async: ^1.13.3
  collection: ^1.14.2
  grpc:
    path: ../
  protobuf: ^0.7.0

dev_dependencies:
  test: ^0.12.0
