name: interop
description: Dart gRPC interoperability test suite.
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^1.5.0
  async: '>=1.13.3 <3.0.0'
  collection: ^1.14.2
  grpc:
    path: ../
  protobuf: ^0.9.0