name: interop
description: Dart gRPC interoperability test suite.
publish_to: none

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  args: ^1.5.2
  async: ^2.2.0
  collection: ^1.14.11
  grpc:
    path: ../
  protobuf: ^2.0.0-nullsafety

dev_dependencies:
  test: ^1.6.4
